import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_components/NavBar";
import AppProvider from "./_components/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("root layout");

  return (
    <html lang="en">
      <body>
        <AppProvider>
          <NavBar />
          <div className="max-w-2/3 mx-auto py-3">{children}</div>
        </AppProvider>
      </body>
    </html>
  );
}
