const express = require("express");
const homeController = require("../controllers/home.controller");
const userController = require("../controllers/user.controller");
const productController = require("../controllers/product.controller");
const router = express.Router();
router.get("/", homeController.index);
router.get("/users", userController.index);
router.get("/users/:id", userController.find);
router.post("/users", userController.create);
router.get("/products", productController.index);
module.exports = router;
